# Refactored from Code Base by https://github.com/ubicomplab/rPPG-Toolbox 
BASE: ['']
TOOLBOX_MODE: "train_and_test"  # "train_and_test"  or "only_test"
TRAIN:
  BATCH_SIZE: 8
  EPOCHS: 25
  LR: 0.01
  MODEL_FILE_NAME: PURE_PURE_PURE_physnet_diffnormalized
  DATA:
    FS: 30
    DATASET: PURE
    DO_PREPROCESS: False            # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH: "/notebooks/PURE"                     # Raw dataset path, need to be updated
    CACHED_PATH: "/notebooks/PURE/PreprocessedData"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 0.9
    PREPROCESS :
      DATA_TYPE: ['DiffNormalized']         #if use physnet, should be DiffNormalized
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 32                 #only support for factor of 512
      DYNAMIC_DETECTION: False
      DYNAMIC_DETECTION_FREQUENCY : 128
      CROP_FACE: True
      LARGE_FACE_BOX: True
      LARGE_BOX_COEF: 1.5
      H: 64
      W: 64
VALID:
  DATA:
    FS: 30
    DATASET: PURE
    DO_PREPROCESS: False                # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH: "/notebooks/PURE"                     # Raw dataset path, need to be updated
    CACHED_PATH: "/notebooks/PURE/PreprocessedData"  
    EXP_DATA_NAME: ""
    BEGIN: 0.9
    END: 1.0
    PREPROCESS :
      DATA_TYPE: ['DiffNormalized']         #if use physnet, should be DiffNormalized
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 32                 #only support for factor of 512
      DYNAMIC_DETECTION: False
      DYNAMIC_DETECTION_FREQUENCY : 128
      CROP_FACE: True
      LARGE_FACE_BOX: True
      LARGE_BOX_COEF: 1.5
      H: 64
      W: 64
TEST:
  METRICS: ['MAE','RMSE','MAPE','Pearson']
  USE_LAST_EPOCH: False                   # to use provided validation dataset to find the best epoch, should be false
  DATA:
    FS: 30
    DATASET: PURE
    DO_PREPROCESS: False                  # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH: "/notebooks/PURE"                     # Raw dataset path, need to be updated
    CACHED_PATH: "/notebooks/PURE/PreprocessedData"  
    EXP_DATA_NAME: ""
    BEGIN: 0.9
    END: 1.0
    PREPROCESS :
      DATA_TYPE: ['DiffNormalized']         #if use physnet, should be DiffNormalized
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 32                 #only support for factor of 512
      DYNAMIC_DETECTION: False
      DYNAMIC_DETECTION_FREQUENCY : 128
      CROP_FACE: True
      LARGE_FACE_BOX: True
      LARGE_BOX_COEF: 1.5
      H: 64
      W: 64
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: runs/exp
MODEL:
  DROP_RATE: 0.2
  NAME: TimeSformer
  PHYSNET:
    FRAME_NUM: 16
INFERENCE:
  BATCH_SIZE: 4
  EVALUATION_METHOD: "FFT"        # "peak detection" or "peak detection"
  MODEL_PATH: ""
